import { ThemeProvider } from "@/components/theme-provider";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider, QueryCache, MutationCache, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { createBrowserRouter, RouterProvider, Navigate, Outlet, useLocation, useParams, useRouteError, type RouteObject } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";
import { useCurrentProfile, useUserRoleNames } from "@/hooks/useUserManagement";
import { resolveRoleHome } from "@/data/navigation";
import { resolveModuleForPath, useAccessControl } from "@/hooks/useAccessControl";
import { CircleNotch as Loader2, ShieldWarning as ShieldAlert, ArrowsClockwise as RefreshCw, SignIn as LogIn } from '@phosphor-icons/react';
import { Button } from "@/components/ui/button";
 import { lazy, Suspense, useState, useEffect, useRef } from "react";
import ScrollRestorationComponent from "@/components/ScrollRestoration";
import { GlobalErrorBoundary } from "@/components/GlobalErrorBoundary";
import { VersionChecker, manualVersionCheck } from "@/components/VersionChecker";
import PageSkeleton, { DashboardSkeleton } from "@/components/layout/PageSkeleton";
import { clearStalePwaArtifacts } from "@/utils/pwa-utils";
import { publicVitrineRoute } from "./router.public";
