-- ════════════════════════════════════════════════════════════════════════════
-- SUPERSEDED — NO-OP intencional (não recolocar DDL aqui).
--
-- O DDL original desta migration fazia o gate de lead de fornecedor de
-- compute_wave_timeline e compute_min_billing_date chamar
-- get_wave_material_needs — mas get_wave_material_needs chama
-- compute_wave_timeline na primeira instrução (corte_palmilha_start_date pro
-- os_send_date dos itens artesanais), criando recursão mútua infinita
-- compute_wave_timeline ↔ get_wave_material_needs (SQLSTATE 54001, stack depth
-- limit exceeded) em produção, em toda consulta de timeline/prazo.
--
-- Revertido em produção em 2026-07-22 reaplicando as definições da
-- 20260920121000 (ver no-op 20260920160001_rollback-shortage-gate-recursion.sql).
--
-- O fix real — mesmo efeito (gate canônico color-aware), SEM ciclo, via split
-- get_wave_material_needs_core + wrapper — está na
-- 20260920161000_shortage-gate-color-aware-v2.sql.
--
-- Este arquivo fica como no-op só de comentários pra manter o replay de
-- `supabase db push` consistente e o histórico do incidente documentado.
-- ════════════════════════════════════════════════════════════════════════════
