// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== 'undefined';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: { eventsPerSecond: 10 },
    // Heartbeat every 25s prevents the 60s idle-timeout that causes
    // "Stream idle timeout - partial response received" on realtime channels.
    heartbeatIntervalMs: 25_000,
    reconnectAfterMs: (tries: number) => Math.min(tries * 2_000, 30_000),
    timeout: 30_000,
  },
});

// Onda B (faturamento): useSaleOrders ainda chama convert_reservation_to_out
// cru. Interceptar aqui aplica o guard da ficha em TODO call-site sem tocar
// no hook de 2.5k linhas. Sem ficha a baixa não roda; o PV segue.
// Dynamic import evita ciclo com fichaDebitGuard (que importa este client).
const rawRpc = supabase.rpc.bind(supabase);
(supabase as unknown as { rpc: typeof supabase.rpc }).rpc = (async (
  fn: string,
  args?: Record<string, unknown>,
  opts?: unknown,
) => {
  if (fn === 'convert_reservation_to_out') {
    const orderId = typeof args?.p_order_id === 'string' ? args.p_order_id : '';
    if (orderId) {
      const { guardDebitForOrder } = await import('@/lib/fichaDebitGuard');
      const guard = await guardDebitForOrder(orderId);
      if (!guard.allowed) {
        const { toast } = await import('sonner');
        toast.warning(
          `Baixa no faturamento não rodou: ${guard.reason || 'ficha técnica ausente'}. ` +
            'O PV segue; acerte a ficha antes de debitar.',
          { duration: 10000 },
        );
        return { data: { blocked_no_sheet: true }, error: null };
      }
    }
  }
  return rawRpc(fn as never, args as never, opts as never);
}) as typeof supabase.rpc;
